services:
  traefik-kop:
    container_name: traefik-kop
    image: ghcr.io/jittering/traefik-kop:latest
    restart: always
    volumes:
      # Allows the agent to watch local containers spin up/down
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - REDIS_ADDR=${REDIS_ADDR}
      - REDIS_PASS=${REDIS_PASSWORD}
      - REDIS_KEY=${REDIS_KEY}
      - DEBUG=1
      - TRAEFIK_LABELS=true
      # Tell Kop the local IP address of THIS specific server node
      # (Traefik needs to know where to route the traffic over the LAN)
      - BIND_IP=${SERVER_IP}
