services:
  pgsql:
    image: postgres:${POSTGRES_VERSION}
    network_mode: host
    container_name: pgsql
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
