---
services:
  nginx:
    image: nginx:1.25.5-alpine
    container_name: nginx-demo-1
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.nginx-demo-1.loadbalancer.server.port=80"
      - "traefik.http.routers.nginx-demo-1-http.entrypoints=web"
      - "traefik.http.routers.nginx-demo-1-http.rule=Host(`nginx-demo-1.gladwelln.dev`)"
        #- "traefik.http.routers.nginx-demo-1.entrypoints=websecure"
        #- "traefik.http.routers.nginx-demo-1.rule=Host(`nginx-demo-1.gladwelln.dev`)"
        #- "traefik.http.routers.nginx-demo-1.tls=true"
        #- "traefik.http.routers.nginx-demo-1.tls.certresolver=cloudflare"
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
    external: true
