services:
  infisical:
    container_name: infisical
    restart: unless-stopped
    image: infisical/infisical:latest # TODO PIN THIS TO A SPECIFIC TAG
    pull_policy: always
    env_file: .env
    # ports:
    #   - 8080:3001
    environment:
      - NODE_ENV=production
      - DB_CONNECTION_URI=${DB_CONNECTION_URI}
      - REDIS_URL=${REDIS_URL}

    networks:
      - frontend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"   # Rotates the log file once it hits 10 Megabytes
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.infisical.loadbalancer.server.port=8080"
      - "traefik.http.routers.infisical-http.entrypoints=web"
      - "traefik.http.routers.infisical-http.rule=Host(`secrets.gladwelln.dev`)"

networks:
  frontend:
    external: true
