services:
  arcane:
    image: ghcr.io/getarcaneapp/manager:latest
    container_name: arcane
    ports:
      - '3552:3552'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - arcane-data:/app/data
    environment:
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - TZ=${TIME_ZONE}
    # cgroup: host
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.arcane.loadbalancer.server.port=3552"
      - "traefik.http.routers.arcane-http.entrypoints=web"
      - "traefik.http.routers.arcane-http.rule=Host(`arcane.gladwelln.dev`)"
    restart: unless-stopped
    networks:
      - frontend

volumes:
  arcane-data:

networks:
  frontend:
    external: true
