services:
  traefik:
    container_name: traefik
    image: traefik:v3.6.6
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
        #- ./config/conf/:/etc/traefik/conf/
        #- ./config/certs/:/etc/traefik/certs/
    environment:
      - CF_DNS_API_TOKEN=$CF_DNS_API_TOKEN
    networks:
      - frontend
      - backend
    restart: unless-stopped
      #labels:
      #- traefik.enable=true
        #- traefik.http.routers.traefik.tls=true
        #- traefik.http.routers.traefik.entrypoints=websecure
        #- traefik.http.services.traefik.loadbalancer.server.port=8080
        #- traefik.http.routers.traefik.rule=Host(`traefik.$DOMAIN`)

        #- traefik.http.routers.traefik.tls.certresolver=cloudflare
        #- traefik.http.routers.traefik.service=api@internal
        #- traefik.http.routers.traefik.tls.domains[0].main=$DOMAIN
        # - traefik.http.routers.traefik.tls.domains[0].sans=*.$DOMAIN
networks:
  frontend:
    external: true
  backend:
    external: true
