services:
  registry:
    image: registry:2
    container_name: registry
    ports:
      - 5000:5000
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    volumes:
      - registry-data:/var/lib/registry
      - ./config.yml:/etc/docker/registry/config.yml
      - ./auth:/auth:ro
    networks:
      - frontend
    restart: unless-stopped

volumes:
  registry-data:
networks:
  frontend:
    external: true
