services:
  youtrack:
    image: jetbrains/youtrack:2026.1.14118
    container_name: youtrack
    restart: unless-stopped
    user: "13001:13001"
    ports:
      - "3006:8080"
    volumes:
      - ./data:/opt/youtrack/data
      - ./conf:/opt/youtrack/conf
      - ./logs:/opt/youtrack/logs
      - /apps-data/youtrack/backups:/opt/youtrack/backups
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.youtrack.rule=Host(`${YOUTRACK_HOSTNAME}`)"
      - "traefik.http.routers.youtrack.entrypoints=web"
      - "traefik.http.services.youtrack-svc.loadbalancer.server.port=3006"

networks:
  frontend:
    external: true
