services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    container_name: umami
    restart: always
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      DATABASE_TYPE: postgresql
      APP_SECRET: ${APP_SECRET}
    networks:
      - frontend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/heartbeat || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      - traefik.enable=true
      - traefik.http.routers.umami.rule=Host(`analytics.gladwelln.dev`)
      - traefik.http.routers.umami.entrypoints=web
      - traefik.http.services.umami.loadbalancer.server.port=3000
      - traefik.http.services.umami.loadbalancer.healthcheck.path=/api/heartbeat
      - traefik.http.services.umami.loadbalancer.healthcheck.interval=10s
      - traefik.http.services.umami.loadbalancer.healthcheck.timeout=5s

networks:
  frontend:
    external: true