services:
  dbgate:
    image: dbgate/dbgate:latest
    container_name: dbgate
    restart: unless-stopped
    ports:
      - "3005:3000"
    environment:
      - CONNECTIONS=postgres_db,mysql_db,redis_db

      # 1. PostgreSQL Connection
      - LABEL_postgres_db=Production Postgres
      - ENGINE_postgres_db=postgres
      - SERVER_postgres_db=${DB_HOST}
      - PORT_postgres_db=${DB_PORT:-5432}
      - USER_postgres_db=${POSTGRES_USER}
      - PASSWORD_postgres_db=${POSTGRES_PASSWORD}

      # 2. MySQL Connection
      - LABEL_mysql_db=Production MySQL
      - ENGINE_mysql_db=mysql
      - SERVER_mysql_db=${DB_HOST}
      - PORT_mysql_db=3306
      - USER_mysql_db=${MYSQL_USER}
      - PASSWORD_mysql_db=${MYSQL_PASSWORD}

      # 3. Redis Connection
      - LABEL_redis_db=Production Redis
      - ENGINE_redis_db=redis
      - SERVER_redis_db=${DB_HOST}
      - PORT_redis_db=6379
      - USER_redis_db=${REDIS_USER}
      - PASSWORD_redis_db=${REDIS_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dbgate.rule=Host(`db.gladwelln.dev`)"
      - "traefik.http.routers.dbgate.entrypoints=web"
      - "traefik.http.services.dbgate.loadbalancer.server.port=3005"
