services:
  registry-ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - 2002:80
    environment:
      - NGINX_PROXY_PASS_URL=http://192.168.68.9:5000
      - DELETE_IMAGES=true
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry-ui.rule=Host(`registry.gladwelln.dev`)"
      - "traefik.http.routers.registry-ui.entrypoints=web"
      - "traefik.http.services.registry-ui.loadbalancer.server.port=2002"