services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    # ports:
    #   - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable
    volumes:
      - ./uptime-kuma-data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
      - "traefik.http.routers.uptime-kuma-http.entrypoints=web"
      - "traefik.http.routers.uptime-kuma-http.rule=Host(`uptime.gladwelln.dev`)"
    restart: unless-stopped
    networks:
      - frontend

networks:
  frontend:
    external: true