services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio-local
    ports:
      - "9002:9000"  # API will be available on host port 9002
      - "9003:9001"  # Console will be available on host port 9003
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"
    restart: always